from os.path import join
from xdress.utils import apiname

_from_src_dir = lambda x: join('Box2D', 'Box2D', *x.split('/'))

def _api_name_kwargs(src_file_glob):
    return {'srcfiles': _from_src_dir(src_file_glob),
            'incfiles': 'Box2D.h',
            'language': 'c++',
    }

package = 'boxtwodee'
packagedir = 'boxtwodee'
includes = [join('.', 'Box2D'), join('.', 'Box2D', 'Box2D'),
            _from_src_dir('Common'),
            _from_src_dir('Collision'), _from_src_dir('Collision/Shapes'),
            _from_src_dir('Dynamics'), _from_src_dir('Dynamics/Contacts'),
            _from_src_dir('Dynamics/Joints'),
            _from_src_dir('Rope')]

plugins = ('xdress.autoall', 'xdress.pep8names', 'xdress.cythongen',)

extra_types = 'boxtwodee_extra_types'  # non-default value

dtypes = [
    'int8', 'int16', 'int32',
    'uint8', 'uint16', 'uint32',
    'float32', 'float64',
    'b2AABB', 'b2Block', 'b2BodyDef', 'b2Chunk', 'b2ClipVertex', 'b2Color',
    'b2ContactEdge', 'b2ContactFeature', 'b2ContactID', 'b2ContactImpulse',
    'b2ContactPositionConstraint', 'b2ContactRegister', 'b2ContactSolverDef',
    'b2ContactVelocityConstraint', 'b2DistanceInput', 'b2DistanceJointDef',
    'b2DistanceOutput', 'b2DistanceProxy', 'b2EPAxis', 'b2EPCollider',
    'b2Filter', 'b2FixtureDef', 'b2FixtureProxy', 'b2FrictionJointDef',
    'b2GearJointDef', 'b2Jacobian', 'b2JointDef', 'b2JointEdge', 'b2Manifold',
    'b2ManifoldPoint', 'b2MassData', 'b2Mat22', 'b2Mat33', 'b2MotorJointDef',
    'b2MouseJointDef', 'b2Pair', 'b2Position', 'b2PositionSolverManifold',
    'b2PrismaticJointDef', 'b2Profile', 'b2PulleyJointDef', 'b2RayCastInput',
    'b2RayCastOutput', 'b2ReferenceFace', 'b2RevoluteJointDef', 'b2RopeDef',
    'b2RopeJointDef', 'b2Rot', 'b2SeparationFunction', 'b2Simplex',
    'b2SimplexCache', 'b2SimplexVertex', 'b2SolverData', 'b2StackEntry',
    'b2Sweep', 'b2TempPolygon', 'b2TimeStep', 'b2TOIInput', 'b2TOIOutput',
    'b2Transform', 'b2TreeNode', 'b2Vec2', 'b2Vec3', 'b2Velocity',
    'b2VelocityConstraintPoint', 'b2Version', 'b2WeldJointDef',
    'b2WheelJointDef', 'b2WorldManifold', 'b2WorldQueryWrapper',
    'b2WorldRayCastWrapper',
]

stlcontainers = []

dtypes_module = 'dt'
stlcontainers_module = 'stlc'
variables = []

functions = []

classes = [
    # Structs
    apiname(srcname='b2AABB', tarname='BoxTwoAABB',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2Block', tarname='BoxTwoBlock',
            **_api_name_kwargs('Common/b2BlockAllocator*')),
    apiname(srcname='b2BodyDef', tarname='BoxTwoBodyDef',
            **_api_name_kwargs('Dynamics/b2Body*')),
    apiname(srcname='b2Chunk', tarname='BoxTwoChunk',
            **_api_name_kwargs('Common/b2BlockAllocator*')),
    apiname(srcname='b2ClipVertex', tarname='BoxTwoClipVertex',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2Color', tarname='BoxTwoColor',
            **_api_name_kwargs('Common/b2Draw*')),
    apiname(srcname='b2ContactEdge', tarname='BoxTwoContactEdge',
            **_api_name_kwargs('Dynamics/Contacts/b2Contact*')),
    apiname(srcname='b2ContactFeature', tarname='BoxTwoContactFeature',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2ContactID', tarname='BoxTwoContactID',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2ContactImpulse', tarname='BoxTwoContactImpulse',
            **_api_name_kwargs('Dynamics/b2WorldCallbacks*')),
    apiname(srcname='b2ContactPositionConstraint',
            tarname='BoxTwoContactPositionConstraint',
            **_api_name_kwargs('Dynamics/Contacts/b2ContactSolver*')),
    apiname(srcname='b2ContactRegister', tarname='BoxTwoContactRegister',
            **_api_name_kwargs('Dynamics/Contacts/b2Contact*')),
    apiname(srcname='b2ContactSolverDef', tarname='BoxTwoContactSolverDef',
            **_api_name_kwargs('Dynamics/Contacts/b2ContactSolver*')),
    apiname(srcname='b2ContactVelocityConstraint',
            tarname='BoxTwoContactVelocityConstraint',
            **_api_name_kwargs('Dynamics/Contacts/b2ContactSolver*')),
    apiname(srcname='b2DistanceInput', tarname='BoxTwoDistanceInput',
            **_api_name_kwargs('Collision/b2Distance*')),
    apiname(srcname='b2DistanceJointDef', tarname='BoxTwoDistanceJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2DistanceJoint*')),
    apiname(srcname='b2DistanceOutput', tarname='BoxTwoDistanceOutput',
            **_api_name_kwargs('Collision/b2Distance*')),
    apiname(srcname='b2DistanceProxy', tarname='BoxTwoDistanceProxy',
            **_api_name_kwargs('Collision/b2Distance*')),
    apiname(srcname='b2EPAxis', tarname='BoxTwoEPAxis',
            **_api_name_kwargs('Collision/b2CollideEdge*')),
    apiname(srcname='b2EPCollider', tarname='BoxTwoEPCollider',
            **_api_name_kwargs('Collision/b2CollideEdge*')),
    apiname(srcname='b2Filter', tarname='BoxTwoFilter',
            **_api_name_kwargs('Dynamics/b2Fixture*')),
    apiname(srcname='b2FixtureDef', tarname='BoxTwoFixtureDef',
            **_api_name_kwargs('Dynamics/b2Body*')),
    apiname(srcname='b2FixtureProxy', tarname='BoxTwoFixtureProxy',
            **_api_name_kwargs('Dynamics/b2Fixture*')),
    apiname(srcname='b2FrictionJointDef', tarname='BoxTwoFrictionJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2FrictionJoint*')),
    apiname(srcname='b2GearJointDef', tarname='BoxTwoGearJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2GearJoint*')),
    apiname(srcname='b2Jacobian', tarname='BoxTwoJacobian',
            **_api_name_kwargs('Dynamics/Joints/b2Joint*')),
    apiname(srcname='b2JointDef', tarname='BoxTwoJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2Joint*')),
    apiname(srcname='b2JointEdge', tarname='BoxTwoJointEdge',
            **_api_name_kwargs('Dynamics/Joints/b2Joint*')),
    apiname(srcname='b2Manifold', tarname='BoxTwoManifold',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2ManifoldPoint', tarname='BoxTwoManifoldPoint',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2MassData', tarname='BoxTwoMassData',
            **_api_name_kwargs('Collision/Shapes/b2Shape*')),
    apiname(srcname='b2Mat22', tarname='BoxTwoMat22',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2Mat33', tarname='BoxTwoMat33',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2MotorJointDef', tarname='BoxTwoMotorJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2MotorJoint*')),
    apiname(srcname='b2MouseJointDef', tarname='BoxTwoMouseJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2MouseJoint*')),
    apiname(srcname='b2Pair', tarname='BoxTwoPair',
            **_api_name_kwargs('Collision/b2BroadPhase*')),
    apiname(srcname='b2Position', tarname='BoxTwoPosition',
            **_api_name_kwargs('Dynamics/b2TimeStep*')),
    apiname(srcname='b2PositionSolverManifold',
            tarname='BoxTwoPositionSolverManifold',
            **_api_name_kwargs('Dynamics/Contacts/b2ContactSolver*')),
    apiname(srcname='b2PrismaticJointDef', tarname='BoxTwoPrismaticJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2PrismaticJoint*')),
    apiname(srcname='b2Profile', tarname='BoxTwoProfile',
            **_api_name_kwargs('Dynamics/b2TimeStep*')),
    apiname(srcname='b2PulleyJointDef', tarname='BoxTwoPulleyJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2PulleyJoint*')),
    apiname(srcname='b2RayCastInput', tarname='BoxTwoRayCastInput',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2RayCastOutput', tarname='BoxTwoRayCastOutput',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2ReferenceFace', tarname='BoxTwoReferenceFace',
            **_api_name_kwargs('Collision/b2CollideEdge*')),
    apiname(srcname='b2RevoluteJointDef', tarname='BoxTwoRevoluteJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2RevoluteJoint*')),
    apiname(srcname='b2RopeDef', tarname='BoxTwoRopeDef',
            **_api_name_kwargs('Rope/b2Rope*')),
    apiname(srcname='b2RopeJointDef', tarname='BoxTwoRopeJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2RopeJoint*')),
    apiname(srcname='b2Rot', tarname='BoxTwoRot',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2SeparationFunction', tarname='BoxTwoSeparationFunction',
            **_api_name_kwargs('Collision/b2TimeOfImpact*')),
    apiname(srcname='b2Simplex', tarname='BoxTwoSimplex',
            **_api_name_kwargs('Collision/b2Distance*')),
    apiname(srcname='b2SimplexCache', tarname='BoxTwoSimplexCache',
            **_api_name_kwargs('Collision/b2Distance*')),
    apiname(srcname='b2SimplexVertex', tarname='BoxTwoSimplexVertex',
            **_api_name_kwargs('Collision/b2Distance*')),
    apiname(srcname='b2SolverData', tarname='BoxTwoSolverData',
            **_api_name_kwargs('Dynamics/b2TimeStep*')),
    apiname(srcname='b2StackEntry', tarname='BoxTwoStackEntry',
            **_api_name_kwargs('Common/b2StackAllocator*')),
    apiname(srcname='b2Sweep', tarname='BoxTwoSweep',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2TempPolygon', tarname='BoxTwoTempPolygon',
            **_api_name_kwargs('Collision/b2CollideEdge*')),
    apiname(srcname='b2TimeStep', tarname='BoxTwoTimeStep',
            **_api_name_kwargs('Dynamics/b2TimeStep*')),
    apiname(srcname='b2TOIInput', tarname='BoxTwoTOIInput',
            **_api_name_kwargs('Collision/b2TimeOfImpact*')),
    apiname(srcname='b2TOIOutput', tarname='BoxTwoTOIOutput',
            **_api_name_kwargs('Collision/b2TimeOfImpact*')),
    apiname(srcname='b2Transform', tarname='BoxTwoTransform',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2TreeNode', tarname='BoxTwoTreeNode',
            **_api_name_kwargs('Collision/b2DynamicTree*')),
    apiname(srcname='b2Vec2', tarname='BoxTwoVec2',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2Vec3', tarname='BoxTwoVec3',
            **_api_name_kwargs('Common/b2Math*')),
    apiname(srcname='b2Velocity', tarname='BoxTwoVelocity',
            **_api_name_kwargs('Dynamics/b2TimeStep*')),
    apiname(srcname='b2VelocityConstraintPoint',
            tarname='BoxTwoVelocityConstraintPoint',
            **_api_name_kwargs('Dynamics/Contacts/b2ContactSolver*')),
    apiname(srcname='b2Version', tarname='BoxTwoVersion',
            **_api_name_kwargs('Common/b2Settings*')),
    apiname(srcname='b2WeldJointDef', tarname='BoxTwoWeldJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2WeldJoint*')),
    apiname(srcname='b2WheelJointDef', tarname='BoxTwoWheelJointDef',
            **_api_name_kwargs('Dynamics/Joints/b2WheelJoint*')),
    apiname(srcname='b2WorldManifold', tarname='BoxTwoWorldManifold',
            **_api_name_kwargs('Collision/b2Collision*')),
    apiname(srcname='b2WorldQueryWrapper', tarname='BoxTwoWorldQueryWrapper',
            **_api_name_kwargs('Dynamics/b2World*')),
    apiname(srcname='b2WorldRayCastWrapper', tarname='BoxTwoWorldRayCastWrapper',
            **_api_name_kwargs('Dynamics/b2World*')),

    # Classes
    apiname(srcname='b2BlockAllocator', tarname='BoxTwoBlockAllocator',
            **_api_name_kwargs('Common/b2BlockAllocator*')),
    apiname(srcname='b2Draw', tarname='BoxTwoDraw',
            **_api_name_kwargs('Common/b2Draw*')),
    apiname(srcname='b2StackAllocator', tarname='BoxTwoStackAllocator',
            **_api_name_kwargs('Common/b2StackAllocator*')),
    apiname(srcname='b2Timer', tarname='BoxTwoTimer',
            **_api_name_kwargs('Common/b2Timer*')),
    apiname(srcname='b2Shape', tarname='BoxTwoShape',
            **_api_name_kwargs('Collision/Shapes/b2Shape*')),
    apiname(srcname='b2ChainShape', tarname='BoxTwoChainShape',
            **_api_name_kwargs('Collision/Shapes/b2ChainShape*')),
    apiname(srcname='b2CircleShape', tarname='BoxTwoCircleShape',
            **_api_name_kwargs('Collision/Shapes/b2CircleShape*')),
    apiname(srcname='b2EdgeShape', tarname='BoxTwoEdgeShape',
            **_api_name_kwargs('Collision/Shapes/b2EdgeShape*')),
    apiname(srcname='b2PolygonShape', tarname='BoxTwoPolygonShape',
            **_api_name_kwargs('Collision/Shapes/b2PolygonShape*')),
    apiname(srcname='b2BroadPhase', tarname='BoxTwoBroadPhase',
            **_api_name_kwargs('Collision/b2BroadPhase*')),
    apiname(srcname='b2DynamicTree', tarname='BoxTwoDynamicTree',
            **_api_name_kwargs('Collision/b2DynamicTree*')),
    apiname(srcname='b2Contact', tarname='BoxTwoContact',
            **_api_name_kwargs('Dynamics/Contacts/b2Contact*')),
    apiname(srcname='b2ChainAndCircleContact',
            tarname='BoxTwoChainAndCircleContact',
            **_api_name_kwargs('Dynamics/Contacts/b2ChainAndCircleContact*')),
    apiname(srcname='b2ChainAndPolygonContact',
            tarname='BoxTwoChainAndPolygonContact',
            **_api_name_kwargs('Dynamics/Contacts/b2ChainAndPolygonContact*')),
    apiname(srcname='b2CircleContact', tarname='BoxTwoCircleContact',
            **_api_name_kwargs('Dynamics/Contacts/b2CircleContact*')),
    apiname(srcname='b2ContactSolver', tarname='BoxTwoContactSolver',
            **_api_name_kwargs('Dynamics/Contacts/b2ContactSolver*')),
    apiname(srcname='b2EdgeAndCircleContact',
            tarname='BoxTwoEdgeAndCircleContact',
            **_api_name_kwargs('Dynamics/Contacts/b2EdgeAndCircleContact*')),
    apiname(srcname='b2EdgeAndPolygonContact',
            tarname='BoxTwoEdgeAndPolygonContact',
            **_api_name_kwargs('Dynamics/Contacts/b2EdgeAndPolygonContact*')),
    apiname(srcname='b2PolygonAndCircleContact',
            tarname='BoxTwoPolygonAndCircleContact',
            **_api_name_kwargs('Dynamics/Contacts/b2PolygonAndCircleContact*')),
    apiname(srcname='b2PolygonContact', tarname='BoxTwoPolygonContact',
            **_api_name_kwargs('Dynamics/Contacts/b2PolygonContact*')),
    apiname(srcname='b2Joint', tarname='BoxTwoJoint',
            **_api_name_kwargs('Dynamics/Joints/b2Joint*')),
    apiname(srcname='b2DistanceJoint', tarname='BoxTwoDistanceJoint',
            **_api_name_kwargs('Dynamics/Joints/b2DistanceJoint*')),
    apiname(srcname='b2FrictionJoint', tarname='BoxTwoFrictionJoint',
            **_api_name_kwargs('Dynamics/Joints/b2FrictionJoint*')),
    apiname(srcname='b2GearJoint', tarname='BoxTwoGearJoint',
            **_api_name_kwargs('Dynamics/Joints/b2GearJoint*')),
    apiname(srcname='b2MotorJoint', tarname='BoxTwoMotorJoint',
            **_api_name_kwargs('Dynamics/Joints/b2MotorJoint*')),
    apiname(srcname='b2MouseJoint', tarname='BoxTwoMouseJoint',
            **_api_name_kwargs('Dynamics/Joints/b2MouseJoint*')),
    apiname(srcname='b2PrismaticJoint', tarname='BoxTwoPrismaticJoint',
            **_api_name_kwargs('Dynamics/Joints/b2PrismaticJoint*')),
    apiname(srcname='b2PulleyJoint', tarname='BoxTwoPulleyJoint',
            **_api_name_kwargs('Dynamics/Joints/b2PulleyJoint*')),
    apiname(srcname='b2RevoluteJoint', tarname='BoxTwoRevoluteJoint',
            **_api_name_kwargs('Dynamics/Joints/b2RevoluteJoint*')),
    apiname(srcname='b2RopeJoint', tarname='BoxTwoRopeJoint',
            **_api_name_kwargs('Dynamics/Joints/b2RopeJoint*')),
    apiname(srcname='b2WeldJoint', tarname='BoxTwoWeldJoint',
            **_api_name_kwargs('Dynamics/Joints/b2WeldJoin*')),
    apiname(srcname='b2WheelJoint', tarname='BoxTwoWheelJoint',
            **_api_name_kwargs('Dynamics/Joints/b2WheelJoint*')),
    apiname(srcname='b2Body', tarname='BoxTwoBody',
            **_api_name_kwargs('Dynamics/b2Body*')),
    apiname(srcname='b2ContactManager', tarname='BoxTwoContactManager',
            **_api_name_kwargs('Dynamics/b2ContactManager*')),
    apiname(srcname='b2Fixture', tarname='BoxTwoFixture',
            **_api_name_kwargs('Dynamics/b2Fixture*')),
    apiname(srcname='b2World', tarname='BoxTwoWorld',
            **_api_name_kwargs('Dynamics/b2World*')),
    apiname(srcname='b2DestructionListener',
            tarname='BoxTwoDestructionListener',
            **_api_name_kwargs('Dynamics/b2WorldCallbacks*')),
    apiname(srcname='b2ContactFilter', tarname='BoxTwoContactFilter',
            **_api_name_kwargs('Dynamics/b2WorldCallbacks*')),
    apiname(srcname='b2ContactListener', tarname='BoxTwoContactListener',
            **_api_name_kwargs('Dynamics/b2WorldCallbacks*')),
    apiname(srcname='b2QueryCallback', tarname='BoxTwoQueryCallback',
            **_api_name_kwargs('Dynamics/b2WorldCallbacks*')),
    apiname(srcname='b2RayCastCallback', tarname='BoxTwoRayCastCallback',
            **_api_name_kwargs('Dynamics/b2WorldCallbacks*')),
    apiname(srcname='b2Rope', tarname='BoxTwoRope',
            **_api_name_kwargs('Rope/b2Rope*')),
]

del _from_src_dir
del _api_name_kwargs
del join
del apiname
